import { Article } from '../../models/article';

export const ARTICLES: Article[] = [
  // ── MENSTRUAL PHASE ──────────────────────────────────────────────────
  {
    slug: 'understanding-your-period',
    phase: 'menstrual',
    title: 'Understanding Your Period',
    summary: 'What actually happens in your body during menstruation, and why symptoms like cramps and fatigue occur.',
    readTimeMinutes: 4,
    tags: ['period', 'hormones', 'basics'],
    sources: [
      { label: 'American College of Obstetricians and Gynecologists (ACOG)', url: 'https://www.acog.org/womens-health/faqs/abnormal-uterine-bleeding' },
      { label: 'NHS – Periods', url: 'https://www.nhs.uk/conditions/periods/' },
    ],
    content: [
      { type: 'paragraph', text: 'Menstruation begins on day 1 of your cycle. The uterine lining (endometrium), which thickened during the previous cycle in preparation for a potential pregnancy, sheds because fertilisation did not occur.' },
      { type: 'heading', text: 'What triggers menstruation?' },
      { type: 'paragraph', text: 'When progesterone and oestrogen levels fall sharply after ovulation, the endometrium loses its hormonal support and breaks down. Prostaglandins — hormone-like chemicals — trigger uterine contractions to expel the lining, which is why cramping occurs.' },
      { type: 'heading', text: 'Common symptoms and why they happen' },
      { type: 'bullet_list', items: ['Cramps: uterine muscle contractions driven by prostaglandins', 'Fatigue: blood loss and low hormones reduce energy', 'Bloating: prostaglandins can affect the bowel', 'Breast tenderness: lingering progesterone effect from previous luteal phase'] },
      { type: 'tip', text: 'Heat therapy (a warm pad on the lower abdomen) can reduce prostaglandin-driven cramp intensity — a simple, evidence-backed remedy.' },
      { type: 'heading', text: 'How long is normal?' },
      { type: 'paragraph', text: 'A typical period lasts 2–7 days with bleeding volume of 30–80ml. Cycles shorter than 21 days or longer than 35 days, or unusually heavy bleeding, are worth discussing with a GP or gynaecologist.' },
    ],
  },
  {
    slug: 'rest-and-restore',
    phase: 'menstrual',
    title: 'Rest & Restore: The Case for Slowing Down',
    summary: 'Why the menstrual phase is biologically designed for lower energy, and how to work with your body rather than against it.',
    readTimeMinutes: 3,
    tags: ['self-care', 'energy', 'rest'],
    sources: [
      { label: 'Dr Stacy Sims – ROAR', url: 'https://www.drstacysims.com/roar' },
      { label: 'Period Power – Maisie Hill', url: 'https://maisiehill.com/books/period-power/' },
    ],
    content: [
      { type: 'paragraph', text: 'Oestrogen and progesterone are both at their lowest during menstruation. This isn\'t a design flaw — it\'s a signal to consolidate, rest, and recover.' },
      { type: 'heading', text: 'What lower hormones mean practically' },
      { type: 'bullet_list', items: ['Lower pain tolerance — you genuinely feel more', 'Reduced glycogen stores — lower physical endurance', 'Greater introspective clarity — inward focus comes naturally'] },
      { type: 'callout', text: 'Research on exercise timing shows that lower-intensity movement during menstruation is associated with better recovery in subsequent phases, not reduced fitness.' },
      { type: 'heading', text: 'Evidence-backed ways to support yourself' },
      { type: 'bullet_list', items: ['Prioritise 8+ hours of sleep — core temperature is lower, making deep sleep easier', 'Reduce high-intensity exercise and replace with walking, yoga, or swimming', 'Eat iron-rich foods to offset blood loss (lentils, spinach, red meat)', 'Limit excess caffeine, which can amplify prostaglandin production'] },
    ],
  },

  // ── FOLLICULAR PHASE ─────────────────────────────────────────────────
  {
    slug: 'follicular-rising-energy',
    phase: 'follicular',
    title: 'The Follicular Phase: Energy on the Rise',
    summary: 'How rising oestrogen transforms your cognition, energy, and mood after your period ends.',
    readTimeMinutes: 4,
    tags: ['follicular', 'oestrogen', 'energy', 'hormones'],
    sources: [
      { label: 'Endocrine Society – Oestrogen overview', url: 'https://www.endocrine.org/patient-engagement/endocrine-library/hormones-and-endocrine-function/reproductive-hormones/estrogen' },
      { label: 'Next Level – Dr Stacy Sims', url: 'https://www.drstacysims.com/next-level' },
    ],
    content: [
      { type: 'paragraph', text: 'As menstruation ends, the pituitary gland releases Follicle Stimulating Hormone (FSH), which triggers several follicles in your ovaries to begin maturing. The dominant follicle produces rising levels of oestrogen — and this hormone is largely responsible for the "spring" feeling of the follicular phase.' },
      { type: 'heading', text: 'What oestrogen does for you' },
      { type: 'bullet_list', items: ['Enhances serotonin and dopamine receptor sensitivity — mood naturally lifts', 'Improves insulin sensitivity — energy use is more efficient', 'Increases collagen production — skin often looks better', 'Promotes tissue elasticity — ideal for physical training'] },
      { type: 'heading', text: 'Cognitive changes you might notice' },
      { type: 'paragraph', text: 'Oestrogen promotes neuroplasticity and verbal fluency. Many people notice they feel sharper, more creative, and better at communicating during this phase. This is a good time to schedule presentations, difficult conversations, or new learning.' },
      { type: 'tip', text: 'The follicular phase is the best time to introduce new exercise routines or skill-based learning — your brain is primed for it.' },
    ],
  },
  {
    slug: 'gut-health-cycle',
    phase: 'follicular',
    title: 'Your Gut and Your Cycle',
    summary: 'The gut–hormone axis is real: how your digestive health and menstrual cycle influence each other.',
    readTimeMinutes: 5,
    tags: ['gut health', 'microbiome', 'oestrogen', 'follicular'],
    sources: [
      { label: 'Journal of Clinical Endocrinology & Metabolism', url: 'https://academic.oup.com/jcem' },
      { label: 'Gut Microbiome Journal', url: 'https://www.cambridge.org/core/journals/gut-microbiome' },
    ],
    content: [
      { type: 'paragraph', text: 'The gut microbiome contains a collection of bacteria responsible for metabolising oestrogen — sometimes called the "estrobolome." When this community is healthy, it helps regulate oestrogen levels circulating in your body.' },
      { type: 'heading', text: 'The oestrogen–gut connection' },
      { type: 'paragraph', text: 'After oestrogen is processed in the liver, it\'s excreted into the gut. Healthy gut bacteria complete its removal. If gut bacteria produce too much beta-glucuronidase (an enzyme), oestrogen gets reabsorbed, potentially elevating circulating levels and worsening hormone-sensitive symptoms.' },
      { type: 'heading', text: 'Supporting gut health across your cycle' },
      { type: 'bullet_list', items: ['Eat 30g of dietary fibre per day to support a diverse microbiome', 'Include fermented foods: yogurt, kefir, kimchi, sauerkraut', 'Limit ultra-processed foods and excess alcohol, which disrupt the estrobolome', 'Prebiotic foods (garlic, onions, oats) feed beneficial bacteria'] },
      { type: 'callout', text: 'Bloating during the menstrual and luteal phases is often gut-related — addressing your gut health year-round can reduce these cyclical symptoms.' },
    ],
  },

  // ── OVULATORY PHASE ──────────────────────────────────────────────────
  {
    slug: 'ovulation-explained',
    phase: 'ovulatory',
    title: 'Ovulation: Your Monthly Peak',
    summary: 'The biology of ovulation, how to recognise it, and why this brief window matters beyond fertility.',
    readTimeMinutes: 4,
    tags: ['ovulation', 'peak', 'fertility', 'hormones'],
    sources: [
      { label: 'ACOG – Ovulation', url: 'https://www.acog.org/womens-health/faqs/fertility-awareness-based-methods-of-family-planning' },
      { label: 'NHS – Fertility awareness methods', url: 'https://www.nhs.uk/conditions/contraception/natural-family-planning/' },
    ],
    content: [
      { type: 'paragraph', text: 'Ovulation occurs when a surge of Luteinising Hormone (LH) causes the dominant follicle to rupture and release a mature egg. The egg lives for 12–24 hours, but because sperm can survive for 3–5 days, the fertile window spans roughly 5 days before ovulation to 1 day after.' },
      { type: 'heading', text: 'Physical signs of ovulation' },
      { type: 'bullet_list', items: ['Cervical mucus becomes clear, slippery, and stretchy ("egg white" texture)', 'Basal body temperature rises by 0.2–0.5°C after ovulation', 'Mild one-sided pelvic pain (mittelschmerz) in some people', 'Increased libido — a biological signal'] },
      { type: 'heading', text: 'Beyond fertility: why ovulation matters' },
      { type: 'paragraph', text: 'Ovulation is the only source of progesterone in a natural cycle. Without it, the luteal phase cannot produce adequate progesterone, which has wide-ranging effects on mood, sleep, bone density, and cardiovascular health. Regular ovulation is a marker of overall hormonal health.' },
      { type: 'tip', text: 'Ovulation can be delayed or suppressed by: high stress, undereating, excessive exercise, illness, or significant weight change.' },
    ],
  },
  {
    slug: 'peak-performance-ovulatory',
    phase: 'ovulatory',
    title: 'Physical Performance at Ovulation',
    summary: 'Peak oestrogen at ovulation makes this the strongest phase of your physical cycle — how to make the most of it.',
    readTimeMinutes: 3,
    tags: ['exercise', 'performance', 'ovulatory', 'strength'],
    sources: [
      { label: 'British Journal of Sports Medicine – Sex hormones and exercise', url: 'https://bjsm.bmj.com' },
      { label: 'Dr Stacy Sims – Female physiology', url: 'https://www.drstacysims.com' },
    ],
    content: [
      { type: 'paragraph', text: 'Oestrogen reaches its cycle peak just before ovulation. This hormone enhances muscle protein synthesis, increases pain tolerance, and improves cardiovascular efficiency — making the ovulatory phase your physical peak.' },
      { type: 'heading', text: 'What this means for training' },
      { type: 'bullet_list', items: ['Strength and power output is highest — good time for personal bests', 'Reaction time and coordination are optimised', 'Pain tolerance is elevated — intense sessions feel more manageable', 'Recovery is faster due to higher collagen synthesis'] },
      { type: 'callout', text: 'One caveat: the ACL ligament is slightly more lax at ovulation due to oestrogen\'s effect on connective tissue. Ensure warm-ups include activation exercises, especially for high-impact sport.' },
      { type: 'heading', text: 'Practical recommendations' },
      { type: 'bullet_list', items: ['Schedule strength training, HIIT, or sport competitions during this window', 'Take advantage of increased motivation and confidence', 'Maintain adequate protein intake (1.6–2.0g per kg body weight) to support muscle synthesis'] },
    ],
  },

  // ── LUTEAL PHASE ─────────────────────────────────────────────────────
  {
    slug: 'understanding-luteal-pms',
    phase: 'luteal',
    title: 'Understanding the Luteal Phase & PMS',
    summary: 'What causes PMS symptoms in the luteal phase, and evidence-based ways to reduce their impact.',
    readTimeMinutes: 5,
    tags: ['luteal', 'PMS', 'progesterone', 'symptoms'],
    sources: [
      { label: 'RCOG – PMS guidelines', url: 'https://www.rcog.org.uk/guidance/browse-all-guidance/green-top-guidelines/management-of-premenstrual-syndrome-green-top-guideline-no-48/' },
      { label: "Journal of Women's Health", url: 'https://www.liebertpub.com/loi/jwh' },
    ],
    content: [
      { type: 'paragraph', text: 'After ovulation, the ruptured follicle becomes the corpus luteum, which secretes progesterone. Progesterone prepares the uterine lining for implantation. If pregnancy does not occur, the corpus luteum degenerates, and both oestrogen and progesterone drop sharply — triggering menstruation.' },
      { type: 'heading', text: 'Why PMS happens' },
      { type: 'paragraph', text: 'Premenstrual syndrome (PMS) affects up to 75% of people who menstruate. Symptoms arise in the late luteal phase from the interaction between falling hormones and neurotransmitter systems. Progesterone metabolises into allopregnanolone, which in sensitive individuals can disrupt GABA receptors — producing anxiety, irritability, and sleep disruption.' },
      { type: 'heading', text: 'Evidence-based interventions' },
      { type: 'bullet_list', items: ['Regular aerobic exercise reduces PMS severity by up to 50%', 'Calcium supplementation (1,200mg/day) has strong evidence for reducing mood and physical symptoms', 'Magnesium (200–400mg/day) reduces bloating and mood symptoms', 'Reducing caffeine, salt, and alcohol in the late luteal phase reduces fluid retention', 'SSRI medication is first-line for severe PMDD — speak to your GP'] },
      { type: 'callout', text: 'PMDD (Premenstrual Dysphoric Disorder) is a severe form of PMS affecting 3–8% of menstruating people. If symptoms significantly impair your daily life, seek support — it\'s a recognised and treatable condition.' },
    ],
  },
  {
    slug: 'sleep-and-your-cycle',
    phase: 'luteal',
    title: 'Sleep and Your Cycle',
    summary: 'How progesterone, body temperature, and hormonal shifts through the cycle affect your sleep quality.',
    readTimeMinutes: 4,
    tags: ['sleep', 'progesterone', 'luteal', 'wellness'],
    sources: [
      { label: 'Sleep Foundation – Menstrual cycle and sleep', url: 'https://www.sleepfoundation.org/women-sleep/menstrual-cycle-and-sleep' },
      { label: 'National Sleep Foundation', url: 'https://www.thensf.org' },
    ],
    content: [
      { type: 'paragraph', text: 'Sleep quality varies significantly across the menstrual cycle. Progesterone — dominant in the luteal phase — has a sedative effect and raises core body temperature. Both of these impact sleep architecture.' },
      { type: 'heading', text: 'Phase-by-phase sleep patterns' },
      { type: 'bullet_list', items: ['Menstrual: lower core temp aids sleep onset, but cramps and discomfort disrupt it', 'Follicular: lowest progesterone — often the best sleep quality of the cycle', 'Ovulatory: LH surge may cause brief insomnia in some people', 'Luteal: elevated temperature, REM sleep reduction, night sweats possible in late phase'] },
      { type: 'heading', text: 'Improving luteal phase sleep' },
      { type: 'bullet_list', items: ['Keep bedroom cool (16–19°C) to counteract elevated core temp', 'Avoid alcohol — it fragments sleep and worsens night sweats', 'Magnesium glycinate before bed may ease sleep onset', 'Consistent wake time anchors circadian rhythm regardless of cycle phase'] },
      { type: 'tip', text: 'Tracking your sleep quality alongside your cycle in Bloom can help you identify your personal pattern and plan accordingly.' },
    ],
  },

  // ── NUTRITION ────────────────────────────────────────────────────────
  {
    slug: 'nutrition-menstrual',
    phase: 'menstrual',
    title: 'What to Eat During Your Period',
    summary: 'Blood loss, inflammation, and low energy all have nutritional solutions. What to prioritise and what to limit.',
    readTimeMinutes: 4,
    tags: ['nutrition', 'iron', 'anti-inflammatory', 'period'],
    sources: [
      { label: 'British Nutrition Foundation – Iron', url: 'https://www.nutrition.org.uk/healthy-sustainable-diets/nutrients/iron/' },
      { label: 'NHS – Vitamins and minerals: Iron', url: 'https://www.nhs.uk/conditions/vitamins-and-minerals/iron/' },
      { label: 'Journal of Pain Research – Omega-3 and dysmenorrhoea', url: 'https://www.dovepress.com/journal-of-pain-research-journal' },
    ],
    content: [
      { type: 'paragraph', text: 'During menstruation, your body loses blood and with it iron — a mineral essential for making red blood cells and transporting oxygen. At the same time, elevated prostaglandins drive inflammation and cramping. Nutrition can directly address both.' },
      { type: 'heading', text: 'Prioritise: iron' },
      { type: 'paragraph', text: 'Haem iron (from animal sources) is most readily absorbed, but non-haem iron from plant sources is fully adequate when combined with vitamin C, which significantly increases absorption.' },
      { type: 'bullet_list', items: [
        'Meat & fish: red meat, liver, sardines, mussels',
        'Plant sources: lentils, chickpeas, tofu, tempeh, edamame, pumpkin seeds, fortified cereals, dark leafy greens (spinach, kale)',
        'Boost absorption: pair plant iron sources with vitamin C — squeeze lemon on lentils, add tomatoes or peppers to iron-rich meals',
        'Inhibitors: tea, coffee, and calcium-rich foods consumed at the same time reduce iron absorption — leave a 1-hour gap',
      ]},
      { type: 'heading', text: 'Prioritise: anti-inflammatory foods' },
      { type: 'paragraph', text: 'Omega-3 fatty acids compete with arachidonic acid in the same metabolic pathway that produces prostaglandins. Higher omega-3 intake is associated with reduced period pain severity.' },
      { type: 'bullet_list', items: [
        'Oily fish: salmon, mackerel, sardines (2+ portions per week)',
        'Vegan/vegetarian omega-3: flaxseeds, chia seeds, hemp seeds, walnuts — and consider an algae-based DHA/EPA supplement, which provides the active forms directly',
        'Ginger and turmeric: both have evidence-backed anti-inflammatory effects; add to warm drinks or meals',
        'Reduce: processed foods, refined sugars, and excess red meat, which increase inflammatory arachidonic acid',
      ]},
      { type: 'heading', text: 'Prioritise: magnesium' },
      { type: 'bullet_list', items: [
        'Dark chocolate (70%+), almonds, cashews, sunflower seeds, black beans',
        'Leafy greens: spinach, Swiss chard',
        'All of the above are suitable for vegetarian and vegan diets',
      ]},
      { type: 'tip', text: 'Warm, cooked foods are easier to digest when your gut is more sensitive during menstruation. Soups, stews, and warm grain bowls with legumes tick multiple nutritional boxes at once.' },
      { type: 'heading', text: 'Limit during your period' },
      { type: 'bullet_list', items: [
        'Caffeine: amplifies prostaglandin production and can worsen cramps and anxiety',
        'Alcohol: increases prostaglandin sensitivity and disrupts sleep',
        'Excess salt: contributes to bloating and fluid retention',
        'Refined sugar: spikes and crashes worsen fatigue and mood',
      ]},
    ],
  },

  {
    slug: 'nutrition-follicular',
    phase: 'follicular',
    title: 'Eating for the Follicular Phase',
    summary: 'Rising oestrogen changes how your body handles food. Nutrients that support hormone metabolism, gut health, and energy.',
    readTimeMinutes: 4,
    tags: ['nutrition', 'oestrogen', 'gut health', 'follicular'],
    sources: [
      { label: 'Endocrine Society – Phytoestrogens and lignans', url: 'https://www.endocrine.org/patient-engagement/endocrine-library/hormones-and-endocrine-function/reproductive-hormones/estrogen' },
      { label: 'Nutrients – Cruciferous vegetables and oestrogen metabolism', url: 'https://www.mdpi.com/journal/nutrients' },
      { label: 'Nature – The gut microbiome and oestrogen', url: 'https://www.nature.com/articles/s41586-019-1058-x' },
    ],
    content: [
      { type: 'paragraph', text: 'As oestrogen rises in the follicular phase, insulin sensitivity improves and energy metabolism becomes more efficient. This is also when the gut\'s estrobolome — the community of bacteria responsible for processing used oestrogen — is most active. Supporting it now pays dividends across the whole cycle.' },
      { type: 'heading', text: 'Cruciferous vegetables' },
      { type: 'paragraph', text: 'Broccoli, cauliflower, Brussels sprouts, cabbage, and kale contain indole-3-carbinol (I3C) and its metabolite DIM, which support the liver\'s conversion of oestrogen into its less potent, more easily excreted forms. Aim for 1–2 portions daily during this phase.' },
      { type: 'tip', text: 'Light cooking (steaming, stir-frying) preserves more glucosinolates than boiling. Raw is also effective — add shredded cabbage or broccoli to salads.' },
      { type: 'heading', text: 'Fermented foods and prebiotic fibre' },
      { type: 'paragraph', text: 'A diverse gut microbiome processes spent oestrogen efficiently. Dysbiosis (an imbalanced microbiome) can cause oestrogen to be reabsorbed rather than excreted, elevating circulating levels.' },
      { type: 'bullet_list', items: [
        'Fermented foods: yogurt, kefir (or coconut/oat kefir for vegan), kimchi, sauerkraut, miso, tempeh',
        'Prebiotic foods: garlic, onions, leeks, asparagus, oats, bananas — these feed beneficial bacteria',
        'Aim for 30g dietary fibre per day from varied whole food sources',
      ]},
      { type: 'heading', text: 'Flaxseeds' },
      { type: 'paragraph', text: 'Flaxseeds are the richest dietary source of lignans — plant compounds that act as phytoestrogens, gently modulating oestrogen activity. They also provide omega-3 ALA and fibre. Ground flaxseed is more bioavailable than whole; add 1–2 tablespoons to porridge, smoothies, or yogurt daily.' },
      { type: 'heading', text: 'Zinc' },
      { type: 'paragraph', text: 'Zinc is required for follicle development and the synthesis of oestrogen itself. Needs are higher as follicles mature.' },
      { type: 'bullet_list', items: [
        'Animal sources: oysters (highest), beef, chicken, eggs',
        'Plant sources: pumpkin seeds, hemp seeds, chickpeas, lentils, cashews, oats',
        'Note: plant-based zinc is less bioavailable due to phytates — soaking and sprouting legumes improves absorption',
      ]},
      { type: 'heading', text: 'Complex carbohydrates' },
      { type: 'bullet_list', items: [
        'Oats, quinoa, brown rice, sweet potato, wholegrain bread',
        'Improved insulin sensitivity in this phase means carbohydrates are used efficiently — a good time for higher-carb fuelling around exercise',
      ]},
    ],
  },

  {
    slug: 'nutrition-ovulatory',
    phase: 'ovulatory',
    title: 'Peak Nutrition at Ovulation',
    summary: 'Your highest-demand nutritional window. Protein, zinc, and antioxidants support the LH surge, egg release, and peak physical output.',
    readTimeMinutes: 3,
    tags: ['nutrition', 'protein', 'zinc', 'ovulatory', 'performance'],
    sources: [
      { label: 'Fertility and Sterility – Nutrition and ovulation', url: 'https://www.fertstert.org' },
      { label: 'Journal of Nutrition – Zinc and reproductive health', url: 'https://academic.oup.com/jn' },
      { label: 'British Journal of Sports Medicine – Protein and exercise', url: 'https://bjsm.bmj.com' },
    ],
    content: [
      { type: 'paragraph', text: 'Ovulation is triggered by a surge in luteinising hormone (LH), and the released egg requires robust antioxidant protection. At the same time, peak oestrogen means anabolism is at its highest — your body responds more effectively to protein for muscle synthesis. This brief phase has the highest nutritional return on investment.' },
      { type: 'heading', text: 'Protein' },
      { type: 'paragraph', text: 'Muscle protein synthesis is maximised around ovulation. Aim for 1.6–2.0g of protein per kg of bodyweight, distributed across meals.' },
      { type: 'bullet_list', items: [
        'Animal sources: chicken, fish, eggs, Greek yogurt, cottage cheese',
        'Plant sources: tofu, tempeh, edamame, lentils, chickpeas, black beans, seitan, hemp seeds',
        'Quinoa is one of the few plant foods containing all nine essential amino acids — particularly useful as a base grain',
        'Combining legumes and grains (e.g. rice and lentils, hummus and pitta) provides a complete amino acid profile',
      ]},
      { type: 'heading', text: 'Zinc' },
      { type: 'paragraph', text: 'The LH surge that triggers ovulation requires adequate zinc. Deficiency is associated with disrupted ovulation timing.' },
      { type: 'bullet_list', items: [
        'Animal: oysters, beef, pork, crab',
        'Plant: pumpkin seeds, hemp seeds, cashews, chickpeas, lentils, oats',
      ]},
      { type: 'heading', text: 'Antioxidants' },
      { type: 'paragraph', text: 'The egg cell is particularly vulnerable to oxidative stress at release. Vitamins C and E, selenium, and beta-carotene provide protection.' },
      { type: 'bullet_list', items: [
        'Vitamin C: bell peppers, strawberries, kiwi, citrus, broccoli',
        'Vitamin E: sunflower seeds, almonds, avocado, olive oil, spinach',
        'Selenium: Brazil nuts (just 2 per day meets daily requirements), eggs, tuna, sunflower seeds',
        'Beta-carotene: carrots, sweet potato, butternut squash, spinach',
      ]},
      { type: 'heading', text: 'Fibre for oestrogen clearance' },
      { type: 'paragraph', text: 'As oestrogen peaks and then begins to fall, adequate fibre ensures efficient excretion. This reduces the risk of excess oestrogen being reabsorbed. Aim for 30g daily from whole grains, legumes, vegetables, and fruit.' },
      { type: 'callout', text: 'Digestive sensitivity can be slightly higher around ovulation for some people. Keep meals balanced and avoid very large portions before high-intensity exercise.' },
    ],
  },

  {
    slug: 'nutrition-luteal',
    phase: 'luteal',
    title: 'Eating Through the Luteal Phase',
    summary: 'A higher metabolic rate, increased cravings, and dropping serotonin all have nutritional explanations — and solutions.',
    readTimeMinutes: 5,
    tags: ['nutrition', 'PMS', 'serotonin', 'magnesium', 'luteal', 'cravings'],
    sources: [
      { label: 'RCOG – PMS guidelines', url: 'https://www.rcog.org.uk/guidance/browse-all-guidance/green-top-guidelines/management-of-premenstrual-syndrome-green-top-guideline-no-48/' },
      { label: 'American Journal of Obstetrics & Gynecology – Calcium and PMS', url: 'https://www.ajog.org' },
      { label: 'Journal of Reproductive Medicine – Magnesium and PMS', url: 'https://www.reproductivemedicine.com' },
    ],
    content: [
      { type: 'paragraph', text: 'The luteal phase is nutritionally the most demanding. Progesterone raises your basal metabolic rate by 100–300 kcal per day — which is the physiological basis for increased appetite and cravings, not a lack of willpower. Serotonin dips as progesterone rises, driving cravings for carbohydrates (serotonin\'s precursor, tryptophan, requires a carbohydrate "carrier" to cross the blood-brain barrier). Understanding these mechanisms makes navigating them far easier.' },
      { type: 'heading', text: 'Calcium — the best-evidenced PMS supplement' },
      { type: 'paragraph', text: 'Calcium supplementation at 1,200mg/day has the strongest clinical evidence of any nutritional intervention for PMS, reducing both mood and physical symptoms by up to 48% in randomised trials.' },
      { type: 'bullet_list', items: [
        'Dairy: milk, yogurt, cheese',
        'Plant sources: calcium-set tofu (check the label — coagulated with calcium sulphate), fortified plant milks (oat, soy, almond), fortified orange juice, edamame, white beans, bok choy, almonds',
        'Note: calcium absorption requires adequate vitamin D — consider checking your levels, particularly in winter',
      ]},
      { type: 'heading', text: 'Magnesium' },
      { type: 'paragraph', text: 'Magnesium reduces bloating, fluid retention, and mood symptoms in the late luteal phase. It also supports sleep quality and reduces cramp intensity.' },
      { type: 'bullet_list', items: [
        'Dark chocolate (70%+), almonds, cashews, pumpkin seeds, sunflower seeds',
        'Black beans, lentils, chickpeas',
        'Leafy greens: spinach, Swiss chard, kale',
        'Wholegrains: brown rice, oats, quinoa',
        'All of the above are plant-based — magnesium is one of the most vegan-friendly nutrients',
      ]},
      { type: 'heading', text: 'Vitamin B6 and serotonin support' },
      { type: 'paragraph', text: 'Vitamin B6 is a co-factor in serotonin and dopamine synthesis. Low B6 in the luteal phase is associated with worse mood symptoms. It also helps regulate how the body responds to progesterone.' },
      { type: 'bullet_list', items: [
        'Animal sources: turkey, chicken, tuna, salmon',
        'Plant sources: chickpeas (one of the richest sources), bananas, pistachios, sunflower seeds, potatoes with skin, avocado, fortified nutritional yeast',
      ]},
      { type: 'heading', text: 'Complex carbohydrates for cravings' },
      { type: 'paragraph', text: 'Rather than restricting carbohydrates — which worsens serotonin dips — focus on complex, slow-release sources that sustain blood sugar and provide tryptophan\'s transport mechanism without crashes.' },
      { type: 'bullet_list', items: [
        'Oats, sweet potato, brown rice, wholegrain pasta, lentils',
        'Combine with tryptophan-rich foods: pumpkin seeds, tofu, oats, eggs, turkey, chicken',
        'Eat regularly — gaps longer than 4–5 hours destabilise blood sugar and worsen mood and cravings',
      ]},
      { type: 'tip', text: 'Craving chocolate or salty snacks before your period is partly your body asking for magnesium and sodium. Dark chocolate (70%+) is a genuinely useful food in this phase — it provides magnesium, iron, and some mood-supporting compounds.' },
      { type: 'heading', text: 'Limit in the late luteal phase' },
      { type: 'bullet_list', items: [
        'Caffeine: worsens anxiety, breast tenderness, and disrupts sleep at a time when sleep is already harder',
        'Alcohol: disrupts GABA receptors (already sensitised by allopregnanolone) and worsens mood the following day',
        'Excess salt: promotes water retention and bloating',
        'Refined sugar: rapid blood sugar spikes followed by crashes worsen fatigue and irritability',
      ]},
    ],
  },
];
